apiVersion: v1
kind: Secret
metadata:
  name: tandemqueue-secrets
  namespace: tandemqueue
type: Opaque
stringData:
  SqlServer__ConnectionString: "Server=172.17.110.12;Database=OnlinePay;User ID=sqlUser;Password=;MultipleActiveResultSets=true;"

